/*
 * File: app/view/ExternalLinkSheet.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WordApp.view.ExternalLinkSheet', {
    extend: 'Ext.ActionSheet',

    config: {
        defaults: 'defaults: {\n  handler: function (btn, evt) {\n    actionSheet.hide();\n  } // handler\n}',
        items: [
            {
                xtype: 'button',
                handler: function(button, event) {
                    navigator.app.loadUrl("http://www.merriam-webster.com/dictionary/"+wForm.getRecord().get("name"), { openExternal:true } );
                    /*  window.plugins.webintent.startActivity({
                    action: 'com.google.android.apps.translate.translation.TranslateActivity',
                    extras: {
                    'key_text_input': wForm.getRecord().get("name"),
                    'key_text_output': '',
                    'key_language_from': 'en',
                    'key_language_from': 'de',
                    'key_suggest_translation': '',
                    'key_from_floating_window': ''
                    }
                    }, function(res) { console.log(res);
                    }, function(res) { console.error(res);
                    });*/
                    els.hide();
                },
                text: 'Merriam Webster'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    navigator.app.loadUrl("http://pda.leo.org/?lp=ende&lang=en&searchLoc=0&cmpType=relaxed&relink=off&sectHdr=on&spellToler=&search="+wForm.getRecord().get("name"), { openExternal:true } );
                    els.hide();
                },
                text: 'Leo'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    var extras = {};
                    extras[WebIntent.EXTRA_TEXT] = Ext.getCmp('WordList').getSelection()[0].get('name');
                    window.plugins.webintent.startActivity({
                        action: 'android.intent.action.SEND',
                        extras: extras,
                        type: 'text/plain',
                    },
                    function() {},
                    function(args) {console.dir(args);alert('Failed to open URL via Android Intent')}
                    );
                    els.hide();
                },
                text: 'Send'
            }
        ]
    }

});