/*
 * File: app/view/WordForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WordApp.view.WordForm', {
    extend: 'Ext.form.Panel',

    config: {
        id: 'WordForm',
        ui: 'dark',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton3',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.Viewport.add(els);
                            els.show();
                            remList = function(){
                                els.hide();
                            };
                            document.addEventListener("backbutton", remList, false);
                        },
                        flex: 1,
                        align: 'right',
                        ui: 'action',
                        iconCls: 'bookmarks',
                        iconMask: true,
                        text: 'Links'
                    }
                ]
            },
            {
                xtype: 'textfield',
                label: 'Word',
                name: 'name',
                required: true
            },
            {
                xtype: 'textareafield',
                height: 68,
                label: 'Comment',
                name: 'comment'
            },
            {
                xtype: 'spacer',
                height: 100,
                ui: 'light'
            },
            {
                xtype: 'textareafield',
                height: 165,
                label: 'Description',
                labelAlign: 'top',
                name: 'description',
                readOnly: true
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        itemId: 'mybutton4',
                        ui: 'confirm',
                        text: 'Save'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybutton3Release',
                event: 'release',
                delegate: '#mybutton3'
            },
            {
                fn: 'onSaveButtonRelease',
                event: 'release',
                delegate: '#mybutton4'
            }
        ]
    },

    onMybutton3Release: function(button, e, options) {
        Ext.Viewport.remove(wForm);

    },

    onSaveButtonRelease: function(button, e, options) {
        alert("needs to be overriden");
    }

});