/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({

    requires: [
        'Ext.field.Search'
    ],
    models: [
        'WordModel',
        'QuoteModel'
    ],
    stores: [
        'SyncStore',
        'QuoteSyncStore'
    ],
    views: [
        'MyTabPanel',
        'WordForm',
        'ExternalLinkSheet'
    ],
    name: 'WordApp',
    controllers: [
        'MyController'
    ],

    launch: function() {
        Ext.onReady(function(){
            navigator.splashscreen.hide();
            s = Ext.getCmp("WordList").getStore();
            s.setSyncRemovedRecords(true); // TODO hacky
            s.loadLocal(function(){
                if(s.getCount() == 0){
                    s.loadServer();
                }
            });
            els = new WordApp.view.ExternalLinkSheet();

            s = Ext.getCmp("QuoteList").getStore();
            s.loadLocal(function(){
                if(s.getCount() == 0){
                    s.loadServer();
                }
            });
        });
        Ext.create('WordApp.view.MyTabPanel', {fullscreen: true});
    }

});
