/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WordApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            wordListButton: 'tabbar button[title=\'Words\']',
            quoteListButton: 'tabbar button[title="Quotes"]'
        }
    },

    showEditForm: function(record) {
        wForm = new WordApp.view.WordForm();
        Ext.Viewport.add(wForm);
        if(record != null){
            wForm.setRecord(record);
        }
        Ext.Viewport.setActiveItem(wForm);
        onBackKey = function(){
            Ext.Viewport.remove(wForm);
            document.removeEventListener("backbutton", onBackKey, false);
        };
        document.addEventListener("backbutton", onBackKey, false);
        return wForm;
    },

    updateRecord: function(button, e, options) {
        s = Ext.getStore('offlineSyncStore');
        r = wForm.getRecord();
        vals = wForm.getValues();
        r.set('name', vals.name);
        r.set('comment', vals.comment);
        s.sync();
        Ext.Viewport.remove(wForm);
    },

    addRecord: function(button, e, options) {
        s = Ext.getStore('offlineSyncStore');
        s.add(wForm.getValues());
        s.sync();
        Ext.Viewport.remove(wForm);

    }

});